# -*- coding: utf-8 -*-
{
    'name': "POS NO ORDER DRAFT",
    'summary': """POS NO ORDER DRAFT""",
    'description': """POS NO ORDER DRAFT""",
    'sequence': -100,
    'version': '14.0.2.0.1',
    "category": "Point of Sale",
    'author': "Altapete Solutions",
    'website': "http://altapetesolutions.com/",
    'maintainer': 'Altapete Solutions',
    'company': 'Altapete Solutions',
    'license': 'AGPL-3',
    'depends': ['base', 'point_of_sale', ],
    'data': ['views/assets.xml', ],
    'qweb': ['static/src/xml/pos.xml'],
    'demo': [],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 0,
    'currency': 'PKR',
}