# -*- coding: utf-8 -*-
{
    'name':  'POS Session Summary Report',
    'summary': """PDF Session Summary Report """,
    'description': """PDF Session Summary Report """,
    'sequence': -100,
    'version': '14.0.2.0.2',
    "category": "Point of Sale",
    'author': "Altapete Solutions",
    'website': "http://altapetesolutions.com/",
    'maintainer': 'Altapete Solutions',
    'company': 'Altapete Solutions',
    'license': 'AGPL-3',
    'depends': [
        'point_of_sale',
    ],
    'data': [
        # 'security/security.xml',
        'security/ir.model.access.csv',
        'report/report.xml',
        'report/session_summary_report.xml',
        'wizard/session_summary.xml',
    ],
    'qweb': [],
    'demo': [],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 0,
    'currency': 'PKR',
}
